#!/bin/bash

####################
# functions
####################

function install {
  if yaourt -Qs $1 > /dev/null ; then
    echo "$1 already installed. skipping"
  else
    echo "installing $1"
    yaourt -S --noconfirm $1
  fi
}

####################
# package setup
####################

install wget

if pacman -Qs yaourt > /dev/null ; then
  echo "yaourt already installed. skipping"
else
  echo "=========== YAOURT ==========="

  mkdir tmp
  cd tmp

  wget https://aur.archlinux.org/packages/pa/package-query/package-query.tar.gz
  tar xfz package-query.tar.gz
  cd package-query
  makepkg
  sudo pacman -U --noconfirm package-query*.pkg.tar.xz
  cd ../

  wget https://aur.archlinux.org/packages/ya/yaourt/yaourt.tar.gz
  tar xfz yaourt.tar.gz
  cd yaourt
  makepkg
  sudo pacman -U --noconfirm yaourt*.pkg.tar.xz
  cd ../

  cd ../
  rm -r tmp
fi

install npm

####################
# git setup
####################

echo "============ GIT ============"

install git

####################
# zsh setup
####################

echo "============ ZSH  ============"

install zsh
install zsh-completions

if echo $SHELL | grep -q "zsh" ; then
  echo "zsh already default shell. skipping"
else
  echo "setting zsh to default shell"
  chsh -s /usr/bin/zsh
fi

if [ ! -d ~/.oh-my-zsh ] ; then
  echo "========== OH-MY-ZSH ========="
  git clone --depth=1 https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
fi

###################
# ag setup
###################

echo "============= AG ============="

install the_silver_searcher # just plop this here

####################
# vim setup
####################

echo "============= VIM ============"

install vim
install tidyhtml
sudo npm install -g csslint
sudo npm install -g jsonlint

git config --global core.editor "vim"

####################
# keychain setup
####################

echo "========== KEYCHAIN =========="

install keychain

####################
# font setup
####################

echo "=========== FONTS ============"

install ttf-liberation

####################
# pulseaudio setup
####################

echo "========= PULSEAUDIO ========="

install pulseaudio
install pavucontrol
install pulseaudio-alsa

if lsmod | grep -q "oss" ; then
  rmmod snd_pcm_oss # https://wiki.archlinux.org/index.php/PulseAudio
fi

####################
# mopidy setup
####################

echo "=========== MOPIDY ==========="

install mopidy

install gstreamer0.10
install gstreamer0.10-base
install gstreamer0.10-base-plugins
install gstreamer0.10-good
install gstreamer0.10-good-plugins
install gstreamer0.10-bad
install gstreamer0.10-bad-plugins
install gstreamer0.10-ugly
install gstreamer0.10-python

install mopidy-soundcloud
install mopidy-spotify
install mopidy-youtube

####################
# ncmpcpp setup
####################

echo "=========== NCMPCPP =========="

install ncmpcpp

####################
# cava setup
####################

echo "============ CAVA ============"

install cava

####################
# twitch setup
####################

echo "=========== TWITCH ==========="

install livestreamer
install mpv

####################
# wm setup
####################

echo "============= WM ============="

# stuff for awesome panel
install otf-ipafont
install dzen2-xft-xpm-xinerama-git
install dmenu2

install feh
install compton
install herbstluftwm

install scrot

####################
# chrome setup
####################

echo "=========== CHROME ==========="

install google-chrome

####################
# atom setup
####################

echo "============ ATOM ============"

install atom-editor

apm install -c isotope-ui todo-show sort-lines project-manager language-jade editorconfig color-picker stylus minimap minimap-git-diff

####################
# copy dotfiles
####################

echo "========== DOTFILES =========="

echo "moving build directory to home"
cp -Rf ./dotfiles/. ~/

####################
# post-dotfiles
####################

echo "======== POST DOTFILES ======="

systemctl --user enable mopidy.service

vim +PluginInstall +qall

####################
# end of script
####################

echo "install complete"
