#!/bin/bash

####################
# functions
####################

function install {
  if yaourt -Qs $1 > /dev/null ; then
    echo "$1 already installed. skipping"
  else
    echo "installing $1"
    yaourt -S --noconfirm $1
  fi
}

####################
# git setup
####################

echo "============ GIT ============"

if pacman -Qs git > /dev/null ; then
  echo "git already installed. skipping"
else
  sudo pacman -S git
fi

####################
# yaourt setup
####################

if pacman -Qs yaourt > /dev/null ; then
  echo "yaourt already installed. skipping"
else
  echo "=========== YAOURT ==========="

  mkdir tmp
  cd tmp

  git clone https://aur.archlinux.org/package-query.git
  cd package-query
  makepkg -si
  cd ..

  git clone https://aur.archlinux.org/yaourt.git
  cd yaourt
  makepkg -si
  cd ..

  cd ..
  rm -rf tmp

  yaourt -Syu
fi

####################
# npm setup
####################

echo "============ NPM ============"

install npm

####################
# zsh setup
####################

echo "============ ZSH  ============"

install zsh
install zsh-completions

if echo $SHELL | grep -q "zsh" ; then
  echo "zsh already default shell. skipping"
else
  echo "setting zsh to default shell"
  chsh -s /usr/bin/zsh
fi

if [ ! -d ~/.oh-my-zsh ] ; then
  echo "========== OH-MY-ZSH ========="
  git clone --depth=1 https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
fi

###################
# ag setup
###################

echo "============= AG ============="

install the_silver_searcher

####################
# vim setup
####################

echo "============= VIM ============"

install vim
install tidyhtml
sudo npm install -g csslint
sudo npm install -g jsonlint

git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

git config --global core.editor "vim"

####################
# keychain setup
####################

echo "========== KEYCHAIN =========="

install openssh
install keychain

####################
# font setup
####################

echo "=========== FONTS ============"

install ttf-liberation

####################
# pulseaudio setup
####################

echo "========= PULSEAUDIO ========="

install pulseaudio
install pavucontrol
install pulseaudio-alsa

if lsmod | grep -q "oss" ; then
  rmmod snd_pcm_oss # https://wiki.archlinux.org/index.php/PulseAudio
fi

####################
# mopidy setup
####################

echo "=========== MOPIDY ==========="

install mopidy

install gstreamer0.10
install gstreamer0.10-base
install gstreamer0.10-base-plugins
install gstreamer0.10-good
install gstreamer0.10-good-plugins
install gstreamer0.10-bad
install gstreamer0.10-bad-plugins
install gstreamer0.10-ugly
install gstreamer0.10-python

install mopidy-soundcloud
install mopidy-spotify
install mopidy-youtube

####################
# ncmpcpp setup
####################

echo "=========== NCMPCPP =========="

install ncmpcpp

####################
# cava setup
####################

echo "============ CAVA ============"

install cava

####################
# wm setup
####################

echo "============= WM ============="

install systemd-numlockontty

install otf-ipafont
install dzen2-xft-xpm-xinerama-git
install dmenu2
install xdotool
install numlockx

install feh
install compton
install herbstluftwm

install termite
install scrot
install ranger
install feh

####################
# script stuff
####################

echo "=========== SCRIPT ==========="

install livestreamer
install i3lock-color-git
install rsync
install mpv
install imagemagick

####################
# chrome setup
####################

echo "=========== CHROME ==========="

install google-chrome

####################
# atom setup
####################

echo "============ ATOM ============"

install atom-editor

apm install -c \
  isotope-ui \
  todo-show \
  project-manager \
  language-jade \
  editorconfig \
  color-picker \
  stylus \
  minimap \
  minimap-git-diff \
  minimap-pigments \
  pigments \
  atom-css-comb \
  git-control \
  go-plus \
  language-ejs \
  lines \
  linter \
  linter-jscs \
  minimap-bookmarks \
  minimap-find-and-replace \
  minimap-highlight-selected \
  terminal-plus \
  tool-bar \
  tool-bar-almighty

####################
# copy dotfiles
####################

echo "========== DOTFILES =========="

echo "moving build directory to home"
cp -Rf ./dotfiles/. ~/

####################
# post-dotfiles
####################

echo "======== POST DOTFILES ======="

systemctl --user enable mopidy.service
sudo systemctl enable numLockOnTty.service

vim +PluginInstall +qall

####################
# end of script
####################

echo "install complete"
