#!/bin/bash

set -e

echo "Drive? (/dev/sdd) [Enter]:"
read drive

echo "Name? (prive) [Enter]:"
read name

sudo cryptsetup --type luks open $drive $name
sudo mount -t ext4 /dev/mapper/$name /mnt

sudo rsync -arAXs --info=progress2 --delete \
  --exclude 'Downloads' \
  --exclude 'node_modules' \
  --exclude '.npm' \
  --exclude 'VirtualBox VMs' \
  $HOME /mnt

sudo umount /mnt
sudo cryptsetup close $name

rm ~/.zsh_history

echo "Complete!"
