#!/bin/bash

##############################
## herbstluftwm autostart
##############################

####################
## herbstluft setup
####################

hc() {
    clientsend="$clientsend , $@"
}

hc emit_hook reload
hc keyunbind --all
hc mouseunbind --all
hc unrule -F
hc unlock

####################
## herbstluft colors
####################

hc set frame_bg_normal_color '#1d1f21'
hc set frame_bg_active_color '#1d1f21'
hc set window_border_normal_color '#1d1f21'
hc set window_border_active_color '#c5c8c6'

# spacing
hc set frame_border_width 10
hc set window_border_width 1

hc set snap_distance 10
hc set snap_gap 5
hc set frame_padding 0
hc set frame_gap 0
hc set window_gap 0

hc set frame_transparent_width 0
hc set frame_bg_transparent 1
hc set frame_active_opacity 1
hc set frame_normal_opacity 0

hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

####################
## herbstluft bindings
####################

# set the master key
Mod=Mod4 # super key

# non herbstluft keybindings
hc keybind XF86AudioRaiseVolume spawn sh -c "pactl set-sink-mute 0 false ; pactl set-sink-volume 0 +1%"
hc keybind XF86AudioLowerVolume spawn sh -c "pactl set-sink-mute 0 false ; pactl -- set-sink-volume 0 -1%"
hc keybind XF86AudioMute spawn pactl set-sink-mute 0 toggle

# app launching keybindings
hc keybind $Mod-Return spawn dmenu_run
hc keybind $Mod-space spawn termite

# herbstluftwm management keys
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close

# focusing clients
hc keybind $Mod-a focus left
hc keybind $Mod-s focus down
hc keybind $Mod-w focus up
hc keybind $Mod-d focus right

hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1

# moving clients
hc keybind $Mod-Shift-a shift left
hc keybind $Mod-Shift-s shift down
hc keybind $Mod-Shift-w shift up
hc keybind $Mod-Shift-d shift right

# frames
hc keybind $Mod-q split bottom 0.5
hc keybind $Mod-e split right 0.5
hc keybind $Mod-r remove

# resizing frames
resizestep=0.01
hc keybind $Mod-Left        resize left +$resizestep
hc keybind $Mod-Down        resize down +$resizestep
hc keybind $Mod-Up          resize up +$resizestep
hc keybind $Mod-Right       resize right +$resizestep

# layouting
hc keybind $Mod-t cycle_layout 1
hc keybind $Mod-g floating toggle
hc keybind $Mod-f fullscreen toggle

# mouse bindings
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

####################
## herbstluft tags
####################

tag_names=( 0001 0010 0011 0100 0101 0110 0111 1000 1001 )
tag_keys=( {1..9} 0 )

for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

####################
## herbstluft windows
####################

#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

herbstclient set tree_style '╾│ ├└╼─┐'

####################
## herbstluft monitors
####################

hc detect_monitors

####################
## startup
####################

herbstclient chain $clientsend&

####################
## panel startup
####################

# panel=~/.config/herbstluftwm/panel.sh
# [ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
# for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
#     # start it on each monitor
#     "$panel" $monitor &
# done
